version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: finance-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pengcopengco
      MYSQL_DATABASE: financeportfolio
      MYSQL_USER: devuser
      MYSQL_PASSWORD: pengcopengco
    ports:
      - "3307:3306"  # ✅ 호스트 3307 → 컨테이너 내부 3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5